services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: controlreactor-backend

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      AbstractApi__ApiKey: ${ABSTRACT_API_KEY}