// <auto-generated />
using System;
using ControlReactor.Datos.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlReactor.Datos.Migrations
{
    [DbContext(typeof(ControlReactorDbContext))]
    [Migration("20261008032330_AgregarCodigosVerificacion")]
    partial class AgregarCodigosVerificacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.CodigoVerificacion", b =>
                {
                    b.Property<int>("IdCodigoVerificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCodigoVerificacion"));

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("boolean");

                    b.HasKey("IdCodigoVerificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CodigosVerificacion");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.JugadorPartida", b =>
                {
                    b.Property<int>("IdJugadorPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdJugadorPartida"));

                    b.Property<bool>("EsGanador")
                        .HasColumnType("boolean");

                    b.Property<int>("IdPartida")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.HasKey("IdJugadorPartida");

                    b.HasIndex("IdPartida");

                    b.HasIndex("IdUsuario");

                    b.ToTable("JugadoresPartida");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.Logro", b =>
                {
                    b.Property<int>("IdLogro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLogro"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLogro");

                    b.ToTable("Logros");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.Partida", b =>
                {
                    b.Property<int>("IdPartida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPartida"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LimiteTiempo")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntajeObjetivo")
                        .HasColumnType("integer");

                    b.Property<int>("SegundosCongelamiento")
                        .HasColumnType("integer");

                    b.Property<string>("TipoFinalizacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPartida");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("AvatarSeleccionado")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("boolean");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.UsuarioLogro", b =>
                {
                    b.Property<int>("IdUsuarioLogro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuarioLogro"));

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLogro")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuarioLogro");

                    b.HasIndex("IdLogro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuariosLogros");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.CodigoVerificacion", b =>
                {
                    b.HasOne("ControlReactor.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.JugadorPartida", b =>
                {
                    b.HasOne("ControlReactor.Modelos.Entidades.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("IdPartida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlReactor.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControlReactor.Modelos.Entidades.UsuarioLogro", b =>
                {
                    b.HasOne("ControlReactor.Modelos.Entidades.Logro", "Logro")
                        .WithMany()
                        .HasForeignKey("IdLogro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlReactor.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
